## PyTorch Fundamentals

In [4]:
import torch

In [14]:
# scalar
s = torch.tensor(7)

# back as python int
s.item()

# vector
v = torch.tensor([7, 7])
v.ndim # 1
v.shape

# matrix
m = torch.tensor([[7, 8], [9, 10]])
m.ndim # 2

# tensor
t = torch.tensor([[
    [1,2,3],
    [4,5,6],
    [7,8,9]
], [
  [10, 11, 12],
  [13, 14, 15],
  [16, 17, 18]
]
])
t.ndim # n - count number of square bracket pairs
t.shape

torch.Size([2, 3, 3])

### Random tensors

In [28]:
# random tensor of size (3, 4)
r = torch.rand(3, 4)
r

tensor([[0.4569, 0.7837, 0.5799, 0.4980],
        [0.6000, 0.2731, 0.1154, 0.9526],
        [0.6432, 0.7596, 0.3499, 0.0202]])

In [31]:
i = torch.rand(size=(224, 224, 3))
i.shape, i.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones for masks

In [32]:
z = torch.zeros((4, 4))
z

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
o = torch.ones(1, 4)
o.shape

torch.Size([1, 4])

### Range of tensors

In [42]:
r = torch.arange(start=0, end=110, step=10)
r

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [44]:
tz = torch.zeros_like(input=r)
tz

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [46]:
f32 = torch.tensor([
    3.0, 6.0, 9.0
], dtype=None, device=None, requires_grad=False)
f32.device

device(type='cpu')

In [47]:
f16 = f32.type(torch.half)
f16.dtype

torch.float16

In [52]:
t1 = torch.tensor([1, 2, 3])
torch.mul(t1, 10)

tensor([10, 20, 30])

In [53]:
t1 * t1

tensor([1, 4, 9])

In [ ]:
t2 = torch.tensor([1, 2, 3])

In [68]:
%%time
t1 @ t2

CPU times: user 221 µs, sys: 55 µs, total: 276 µs
Wall time: 255 µs


tensor(14)

In [69]:
%%time
torch.dot(t1, t2)

CPU times: user 174 µs, sys: 45 µs, total: 219 µs
Wall time: 204 µs


tensor(14)

In [70]:
%%time
torch.matmul(t1, t2)

CPU times: user 211 µs, sys: 47 µs, total: 258 µs
Wall time: 227 µs


tensor(14)

### Tensor aggregation

In [55]:
t1.min(), t2.max(), t1.type(torch.float32).mean()

(tensor(1), tensor(3), tensor(2.))

In [57]:
torch.tensor([1.,2.,3.,4.]).mean()

tensor(2.5000)

In [60]:
# Positional min/max, returns index
t1.argmin(), t1.argmax()

(tensor(0), tensor(2))

### Tensor re-shaping
* Reshaping - reshapes an input tensor to a defined shape
* Viewing - returns a view of the input tensor of a certain shape but the memory is kept the same as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - adds `1` dimension to a target tensor
* Permute - retuns a view of the input with dimensions permuted in a certain way

In [71]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [75]:
# add extra dimension
xr = x.reshape(1, 9)
print(xr.shape)
xr2 = x.reshape(9, 1)
print(xr2.shape)

torch.Size([1, 9])
torch.Size([9, 1])


In [76]:
# change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [77]:
# changing z changes x because a view shares the same memory
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [80]:
# stack tensors on top of each other
x_s = torch.stack([x, x, x, x], dim=0)
x_s

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [82]:
xr.squeeze().shape

torch.Size([9])

In [84]:
x_s.flatten().shape

torch.Size([36])

In [89]:
x_s.unsqueeze(0).shape

torch.Size([1, 4, 9])

In [107]:
x_og = torch.rand(size=(224,224,3))

x_p = x_og.permute(2, 0, 1) # shifts axis 0 -> 1, 1->2, 2->0
x_p.shape

torch.Size([3, 224, 224])

In [108]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [112]:
print(x[0])
print(x[0,0])
print(x[0,0,0])
print(x[0,:,0])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
tensor(1)
tensor([1, 4, 7])


In [114]:
print(x[:,:,2])

tensor([[3, 6, 9]])


In [116]:
print(x[:,1,1])

tensor([5])


In [119]:
print(x[:,1,:])

tensor([[4, 5, 6]])


### PyTorch to NumPy


In [122]:
import numpy as np
array = np.arange(1.,8.)
tensor = torch.from_numpy(array) # new memory allocation

In [123]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [124]:
t = torch.ones(7)
nt = t.numpy()
t.dtype, nt.dtype

(torch.float32, dtype('float32'))

### Reproducability

In [125]:
torch.manual_seed(42)
rt1 = torch.randn(8, 4)

torch.manual_seed(42)
rt2 = torch.randn(8, 4)

rt1 == rt2

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Tensors on CPU/GPU

In [126]:
torch.cuda.is_available()

False

In [127]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [128]:
torch.cuda.device_count()

0

In [129]:
t = torch.tensor([1,2,3], device=device)
print(t, t.device)

tensor([1, 2, 3]) cpu


In [131]:
t.to(device)

tensor([1, 2, 3])